version: '3.8'

services:
  app:
    # Image depuis GitHub Container Registry
    image: ghcr.io/cedric/scorpiusproject-docling:latest
    container_name: scorpius-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://scorpius:scorpius@db:5432/scorpius_mvp
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - scorpius-network

  db:
    image: postgres:15-alpine
    container_name: scorpius-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=scorpius
      - POSTGRES_PASSWORD=${DB_PASSWORD:-scorpius}
      - POSTGRES_DB=scorpius_mvp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scorpius -d scorpius_mvp"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scorpius-network

  redis:
    image: redis:7-alpine
    container_name: scorpius-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - scorpius-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: scorpius-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@scorpius.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - scorpius-network
    profiles:
      - tools  # Only start with --profile tools

networks:
  scorpius-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: